services:
  mood-tracker-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mysql
      - RAILS_ENV=development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: mood_tracker
      MYSQL_USER: mood_tracker
      MYSQL_PASSWORD: mood_tracker
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--host=localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app_network

networks:
  app_network: